#!/usr/bin/env php
<?php

declare(strict_types=1);

require_once __DIR__.DIRECTORY_SEPARATOR.'vendor'.DIRECTORY_SEPARATOR.'autoload.php';
require_once __DIR__.DIRECTORY_SEPARATOR.'util.php';

use Symfony\Component\Process\Process;
use Symfony\Component\Process\ExecutableFinder;
use Symfony\Component\Process\Exception\ProcessFailedException;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Helper\ProgressBar;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\SingleCommandApplication;
use Symfony\Component\Console\Style\SymfonyStyle;
use Monolog\Logger;
use Monolog\Handler\StreamHandler;

(new SingleCommandApplication())
    ->setVersion('0.1.0')
    ->addOption('metadata-file', null, InputOption::VALUE_REQUIRED, 'Path to the metadata.json file', '.'.DIRECTORY_SEPARATOR.'metadata.json')
    ->addOption('cookies-file', null, InputOption::VALUE_REQUIRED, 'Path to the youtube.com_cookies.txt file', '.'.DIRECTORY_SEPARATOR.'youtube.com_cookies.txt')
    ->addOption('output-dir', null, InputOption::VALUE_REQUIRED, 'Path where songs will be downloaded', '.'.DIRECTORY_SEPARATOR.'downloads')
    ->addOption('song-id', null, InputOption::VALUE_REQUIRED, 'Download a specific song')
    ->addOption('force', 'f', InputOption::VALUE_NONE, 'Set this option to re-download existing songs')
    ->addOption('log-level', 'l', InputOption::VALUE_REQUIRED, 'Set logging level', Logger::INFO)
    ->setCode(function (InputInterface $input, OutputInterface $output) {
        $logger = new Logger(basename(__FILE__));
        $logger->pushHandler(
            new StreamHandler(
                __DIR__.DIRECTORY_SEPARATOR.basename(__FILE__).'.log',
                Logger::toMonologLevel($input->getOption('log-level'))
            )
        );

        $logger->info('command started');

        $io = new SymfonyStyle($input, $output);
        $io->title('YouTube Music Upload Downloader');

        $data = json_decode(file_get_contents($input->getOption('metadata-file')), true);
        $count = \count($data);
        if (false === $data || 0 === $count) {
            $io->error('Empty or not found metadata-file');

            return Command::INVALID;
        }

        if (!file_exists($input->getOption('cookies-file'))) {
            $io->error('cookies-file not found');

            return Command::INVALID;
        }

        $argSongId = $input->getOption('song-id');

        if ($argSongId) {
            $count = 1;
        }

        $io->text('Will now download '.$count.' songs:');

        $progressBar = new ProgressBar($output);
        $progressBar->setFormat('verbose');
        $progressBar->start($count);

        $ytdlp = (new ExecutableFinder())->find('yt-dlp');
        $cookiesFile = $input->getOption('cookies-file');
        $outputDir = rtrim($input->getOption('output-dir'), DIRECTORY_SEPARATOR);
        $resume = !$input->getOption('force');

        // This is the yt-dlp command, you can add/remove options as needed
        $cmdTemplate = <<<TPL
        %s
        --format bestaudio
        --extract-audio
        --audio-format best
        --audio-quality 0
        --abort-on-error
        --no-playlist
        --ignore-config
        --no-warnings
        --no-progress
        --no-mtime
        --cookies "%s"
        --parse-metadata " %s: %%(meta_artist)s"
        %s
        --embed-metadata
        --embed-thumbnail
        --output "%s.%%(ext)s"
        "%s"
        TPL;

        $albumTemplate = '--parse-metadata " %s: %%(meta_album)s"';

        foreach ($data as $song) {
            try {
                if ($argSongId && $song['id'] !== $argSongId) {
                    continue;
                }

                try {
                    $path = getDownloadedSong($outputDir, $song['id']);

                    if ($resume) {
                        $logger->info('skipped', ['id' => $song['id'], 'song_path' => $path]);
                        $progressBar->advance();
                        continue;
                    }
                } catch (\InvalidArgumentException) {
                    // Do nothing here as it's expected for the song to be not
                    // found in the first place.
                }

                $cmd = str_replace(
                    PHP_EOL,
                    ' ',
                    sprintf(
                        $cmdTemplate,
                        $ytdlp,
                        $cookiesFile,
                        addcslashes($song['artist'], ':'),
                        $song['album'] ? sprintf($albumTemplate, addcslashes($song['album'], ':')) : '',
                        $outputDir.DIRECTORY_SEPARATOR.$song['id'],
                        $song['href']
                    )
                );

                $logger->debug('cmd', ['id' => $song['id'], 'cmd' => $cmd]);

                $proc = Process::fromShellCommandline($cmd);
                $proc->setTimeout(null);
                $proc->setIdleTimeout(null);
                $proc->run();

                $logger->debug('cmd stdout', ['id' => $song['id'], 'stdout' => $proc->getOutput()]);

                if (!$proc->isSuccessful()) {
                    $logger->debug('cmd stderr', ['id' => $song['id'], 'stderr' => $proc->getErrorOutput()]);
                    throw new ProcessFailedException($proc);
                }

                $logger->info('success', [
                    'id' => $song['id'],
                    'song_path' => getDownloadedSong($outputDir, $song['id'])
                ]);
                $progressBar->advance();
            } catch (\Throwable $e) {
                $logger->error('error: '.$e->getMessage(), [
                    'song' => $song,
                    'trace' => $e->getTraceAsString()
                ]);
                throw $e;
            }
        }

        $progressBar->finish();

        $io->newLine(2);
        $io->success('done');
        $logger->info('command finished');

        return Command::SUCCESS;
    })
    ->run();
